config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :owners 

  resources :houses

  resources :locators

  resources :contracts do
    get 'finish_contract', to: 'contracts#finish_contract'
    resources :installments, only: [ :index ]   
  end 

  get 'change_payment_status', to: 'installments#change_payment_status'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :house
  belongs_to :locator

  before_save :set_contract_expiration_date, :set_total_amount
  after_save :set_house_rented
  before_create :set_contract_active
  after_create :create_installment
  
  private

  def set_contract_expiration_date
    self.contract_expiration_date = Date.today + (self.contract_term * 30)
  end

  def set_total_amount
    self.iptu_charge ? self.total_amount = self.reantal_amount + self.iptu_amount : self.total_amount = self.reantal_amount
  end

  def set_contract_active
    self.is_active = true
  end

  def set_house_rented
    self.house.rental_status = true
    self.house.save
  end

  def create_installment
    payment_day = self.payment_date
    self.contract_term.times do 
      @installment = Installment.new
      @installment.amount = set_total_amount
      @installment.payment_day = payment_day
      @installment.contract_id = self.id
      @installment.save
      payment_day += 1.month
    end

  end

end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :owner
  has_many :contracts, dependent: :destroy
end

app/models/installment.rb
class Installment < ApplicationRecord
  belongs_to :contract
end

app/models/locator.rb
class Locator < ApplicationRecord
    has_many :contracts, dependent: :destroy
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_many :houses, dependent: :destroy
    has_many :contracts, through: :houses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
    before_action :authenticate_user! 
    before_action :set_contract, only: [:show, :edit, :destroy, :update]

    def index
      @contracts = Contract.all
    end
  
    def show
    end
  
    def new
        @contract = Contract.new
    end
  
    def create
        @contract = Contract.new(contract_params)
        if @contract.save
            redirect_to contract_path(@contract)
        end
    end
  
    def edit
    end
  
    def update
      if @contract.update(contract_params)
        redirect_to contract_path(@contract)
      else
        render :edit
      end
    end
  
    def destroy
      @contract.destroy
      redirect_to contracts_path
    end

    def finish_contract
      @contract = Contract.find(params[:contract_id])
      set_contract_status(@contract)
      set_house_rental_status(@contract.house)
      redirect_to contracts_path
    end
  
    private

    def set_house_rental_status(house)
      house.rental_status = false
      house.save
    end

    def set_contract_status(contract)
      contract.is_active = false
      contract.save
    end
  
    def set_contract
      @contract = Contract.find(params[:id])
    end
  
    def contract_params
      params.require(:contract).permit(:reantal_amount, :iptu_amount, :contract_expiration_date, :contract_term, :discount, :readjust, :fees, :iptu_charge, :payment_date, :is_active, :total_amount, :house_id, :locator_id)
    end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_house, only: [:show, :edit, :destroy, :update]

    def index
      @houses = House.all
    end
  
    def show
    end
  
    def new
        @house = House.new
    end
  
    def create
        @house = House.new(house_params)
        if @house.save
            redirect_to house_path(@house)
        end
    end
  
    def edit
    end
  
    def update
      if @house.update(house_params)
        redirect_to house_path(@house)
      else
        render :edit
      end
    end
  
    def destroy
      @house.destroy
      redirect_to houses_path
    end
  
    private
  
    def set_house
      @house = House.find(params[:id])
    end
  
    def house_params
      params.require(:house).permit(:description, :address, :rental_status, :owner_id, :house_name)
    end
end

app/controllers/installments_controller.rb
class InstallmentsController < ApplicationController
    before_action :authenticate_user!
    def index 
        @installments = Installment.where(contract_id: params[:contract_id])
    end

    def change_payment_status
        @installment = Installment.find(params[:format])
        @installment.payment_status = true
        if @installment.save
            redirect_to contract_installments_path(@installment.contract)
        end
    end
end

app/controllers/locators_controller.rb
class LocatorsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_locator, only: [:show, :edit, :destroy, :update]

    def index
      @locators = Locator.all
    end
  
    def show
    end
  
    def new
      @locator = Locator.new
    end
  
    def create
      @locator = Locator.new(locator_params)
      if @locator.save
        redirect_to locator_path(@locator)
      end
    end
  
    def edit
    end
  
    def update
      if @locator.update(locator_params)
        redirect_to locator_path(@locator)
      else
        render :edit
      end
    end
  
    def destroy
      @locator.destroy
      redirect_to locators_path
    end
  
    private
  
    def set_locator
      @locator = Locator.find(params[:id])
    end
  
    def locator_params
      params.require(:locator).permit(:name, :cpf, :rg, :birthdate, :address, :email, :phone, :marital_status, :contact_name, :contact_phone, :contact_relation, :contact_address)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_owner, only: [:show, :edit, :destroy, :update]

    def index
      @owners = Owner.all
    end
  
    def show
    end
  
    def new
      @owner = Owner.new
    end
  
    def create
      @owner = Owner.new(owner_params)
      if @owner.save
        redirect_to owner_path(@owner)
      end
    end
  
    def edit
    end
  
    def update
      if @owner.update(owner_params)
        redirect_to owner_path(@owner)
      else
        render :edit
      end
    end
  
    def destroy
      @owner.destroy
      redirect_to owners_path
    end
  
    private
  
    def set_owner
      @owner = Owner.find(params[:id])
    end
  
    def owner_params
      params.require(:owner).permit(:name, :cpf, :rg, :birthdate, :address, :email, :phone, :marital_status)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/_form.html.erb
<div class="container">
    <div class="container-form">
        <%= simple_form_for(@contract) do |f| %>
            <%= f.input :locator_id, collection: Locator.all.map { |locator| ["#{locator.name}", locator.id ]}, label: "Locatário:" %>
            <%= f.input :house_id, collection: House.where(rental_status: false).map { |house| ["#{house.house_name}", house.id ]}, label: "Propriedade:" %>
            <%= f.input :reantal_amount, label: "Valor aluguel:" %>
            <%= f.input :discount, label: "Valor desconto:" %>
            <%= f.input :contract_term, label: "Prazo contrato:" %>
            <%= f.input :payment_date, :order => [ :day, :month, :year ], label: "Data do primeiro pagamento:" %>
            <%= f.input :readjust, collection: ['IGPM', 'IGT'], label: "Reajuste:" %>
            <%= f.input :fees, label: "Multa por atraso:" %>
            <%= f.input :iptu_charge, as: :boolean, checked_value: true, unchecked_value: false, label: "Cobrança de IPTU:" %>
            <%= f.input :iptu_amount, label: "Valor do IPTU:" %>
            <div class="form-actions text-center">
                <%= f.button :submit, "Salvar", class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>
</div>

app/views/contracts/edit.html.erb
<%= render "form", contract: @contract %>

app/views/contracts/index.html.erb
<div class="container mt-4">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Propriedade</th>
        <th scope="col">Locatário</th>
        <th scope="col">Proprietário</th>
        <th scope="col">Valor Mensal</th>
        <th scope="col">Vencimento</th>
        <th scope="col">Situação</th>
        <th scope="col">Visualizar</th>
        <th scope="col">Editar</th>
        <th scope="col">Parcelas</th>
        <th scope="col">Finalizar</th>
      </tr>
    </thead>
    <tbody>
      <% @contracts.each do |contract| %>
        <tr>
            <th scope="row"><%= contract.id %></th>
            <td><%= contract.house.house_name %></td>
            <td><%= contract.locator.name %></td>
            <td><%= contract.house.owner.name %></td>
            <td>R$ <%= contract.total_amount %>0</td>
            <td><%= contract.payment_date.strftime("Dia %d")%></td>
            <td><%= contract.is_active ? "Ativo" : "Encerrado" %></td>
            <td><%= link_to 'Visualizar', contract_path(contract) %></td>
            <td><%= link_to 'Editar', edit_contract_path(contract) %></td>
            <td><%= link_to 'Pagamentos', contract_installments_path(contract) %></td>
            <td><%= link_to 'Finalizar', contract_finish_contract_path(contract) unless contract.is_active == false %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%#= link_to 'Voltar', :back, class: 'btn btn-primary mt-3' %>
</div>

app/views/contracts/new.html.erb
<%= render "form", contract: @contract %>

app/views/houses/_form.html.erb
<div class="container">
    <div class="container-form">
        <%= simple_form_for [ owner, house ] do |f| %>
            <%= f.input :house_name, label: "Propriedade:" %>
            <%= f.input :description, label: "Descrição:" %>
            <%= f.input :address, label: "Endereço:" %>
            <%= f.input :owner_id, collection: Owner.all.map { |owner| ["#{owner.name}", owner.id ]}, label: "Proprietário:" %>
            <div class="form-actions text-center">
                <%= f.button :submit, "Salvar", class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>
</div>

app/views/houses/edit.html.erb
<%= render "form", owner: @owner, house: @house %>

app/views/houses/index.html.erb
<div class="container mt-4">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">Endereço</th>
        <th scope="col">Situação</th>
        <th scope="col">Visualizar</th>
        <th scope="col">Editar</th>
      </tr>
    </thead>
    <tbody>
      <% @houses.each do |house| %>
        <tr>
            <th scope="row"><%= house.id %></th>
            <td><%= house.house_name %></td>
            <td><%= house.address %></td>
            <td><%= house.rental_status ? 'Alugada' : "Disponível" %></td>
            <td><%= link_to 'Visualizar', house_path(house) %></td>
            <td><%= link_to 'Editar', edit_house_path(house) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%#= link_to 'Voltar', :back, class: 'btn btn-primary mt-3' %>
</div>

app/views/houses/new.html.erb
<%= render "form", owner: @owner, house: @house %>

app/views/houses/show.html.erb
<div class="container mt-4">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">descrição</th>
        <th scope="col">Endereço</th>
        <th scope="col">Situação</th>
        <th scope="col">Proprietário</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <th scope="row"><%= @house.id %></th>
          <td><%= @house.house_name %></td>
          <td><%= @house.description %></td>
          <td><%= @house.address %></td>
          <td><%= @house.rental_status ? 'Alugada' : "Disponível" %></td>
          <td><%= @house.owner.name %></td>
        </tr>
    </tbody>
  </table>

  <div class="links text-center">
    <%= link_to 'Editar', edit_house_path(@house), class: 'btn btn-primary mb-3' %>
    <%= link_to "Excluir", @house, method: :delete, data: { confirm: 'Tem certeza que deseja deletar este cliente?' }, class: 'btn btn-danger mb-3' %>
  </div>
</div>

app/views/installments/index.html.erb
<div class="container mt-4">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Data de vencimento</th>
        <th scope="col">Propriedade</th>
        <th scope="col">Valor</th>
        <th scope="col">Contrato</th>
        <th scope="col">Situação</th>
        <th scope="col">Pago</th>
      </tr>
    </thead>
    <tbody>
      <% @installments.each do |installment| %>
        <tr>
            <th scope="row"><%= installment.id %></th>
            <td><%= installment.payment_day.strftime("%d/%b/%y") %></td>
            <td><%= installment.contract.house.house_name %></td>
            <td>R$ <%= installment.contract.total_amount %>0</td>
            <td><%= installment.contract.id %></td>
            <td><%= installment.payment_status ? 'Pago' : "Aberto" %></td>
            <td><%= installment.updated_at.strftime("%d/%b/%y") unless installment.payment_status == false %></td>
            <td><%= link_to 'Pagar', change_payment_status_path(installment) unless installment.payment_status == true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeippertApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/locators/_form.html.erb
<div class="container">
    <div class="container-form">
        <%= simple_form_for(locator) do |f| %>
            <%= f.error_notification %>
            <h3 class="text-center">Cadastro de Locatário</h3>
            <div class="form-inputs">
                <%= f.input :name, label: "Nome:" %>
                <%= f.input :cpf, label: "CPF:" %>
                <%= f.input :rg, label: "RG" %>
                <%= f.input :birthdate, :order => [ :day, :month, :year ], label: "Nascimento:" %>
                <%= f.input :email, label: "Email" %>
                <%= f.input :phone, label: "Telefone" %>
                <%= f.input :address, label: "Endereço" %>
                <%= f.input :marital_status, label: "Estado Cívil" %>

                <%= f.input :contact_name, label: "Contato:" %>
                <%= f.input :contact_phone, label: "Telefone:" %>
                <%= f.input :contact_relation, label: "Relação:" %>
                <%= f.input :contact_address, label: "Endereço" %>
            </div>
            <div class="form-actions text-center">
                <%= f.button :submit, "Enviar", class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>
</div>

app/views/locators/edit.html.erb
<%= render "form", locator: @locator %>

app/views/locators/index.html.erb
<div class="container mt-4">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">RG</th>
        <th scope="col">Visualizar</th>
        <th scope="col">Editar</th>
      </tr>
    </thead>
    <tbody>
      <% @locators.each do |locator| %>
        <tr>
            <th scope="row"><%= locator.id %></th>
            <td><%= locator.name %></td>
            <td><%= locator.cpf %></td>
            <td><%= locator.rg %></td>
            <td><%= link_to 'Visualizar', locator_path(locator) %></td>
            <td><%= link_to 'Editar', edit_locator_path(locator) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%#= link_to 'Voltar', :back, class: 'btn btn-primary mt-3' %>
</div>

app/views/locators/new.html.erb
<%= render "form", locator: @locator %>

app/views/locators/show.html.erb
<div class="container mt-4">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">RG</th>
        <th scope="col">Telefone</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <th scope="row"><%= @locator.id %></th>
          <td><%= @locator.name %></td>
          <td><%= @locator.cpf %></td>
          <td><%= @locator.rg %></td>
          <td><%= @locator.phone %></td>
        </tr>
    </tbody>
  </table>

  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Endereço</th>
        <th scope="col">E-mail</th>
        <th scope="col">Estado Cívil</th>
        <th scope="col">Data de Nascimento</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @locator.address %></td>
          <td><%= @locator.email %></td>
          <td><%= @locator.marital_status %></td>
          <td><%= @locator.birthdate %></td>
        </tr>
    </tbody>
  </table>

    <table class="table table-bordered table-dark">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Telefone</th>
                <th scope="col">Endereço</th>
                <th scope="col">Parentesco</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><%= @locator.contact_name %></td>
                <td><%= @locator.contact_phone %></td>
                <td><%= @locator.contact_address %></td>
                <td><%= @locator.contact_relation %></td>
            </tr>
        </tbody>
    </table>  

  <div class="links text-center">
    <%= link_to 'Editar', edit_locator_path(@locator), class: 'btn btn-primary mb-3' %>
    <%= link_to "Excluir", @locator, method: :delete, data: { confirm: 'Tem certeza que deseja deletar este cliente?' }, class: 'btn btn-danger mb-3' %>
  </div>
</div>

app/views/owners/_form.html.erb
<div class="container">
  <div class="container-form">
  <%= simple_form_for(owner) do |f| %>
    <%= f.error_notification %>
    <h3 class="text-center">Cadastro de Proprietário</h3>
    <div class="form-inputs">
      <%= f.input :name, label: "Nome:" %>
      <%= f.input :cpf, label: "CPF:" %>
      <%= f.input :rg, label: "RG" %>
      <%= f.input :birthdate, :order => [ :day, :month, :year ], label: "Nascimento:" %>
      <%= f.input :email, label: "Email" %>
      <%= f.input :phone, label: "Telefone" %>
      <%= f.input :address, label: "Endereço" %>
      <%= f.input :marital_status, label: "Estado Cívil" %>
    </div>
    <div class="form-actions text-center">
      <%= f.button :submit, "Enviar", class: 'btn btn-primary' %>
    </div>
  <% end %>
  </div>
</div>

app/views/owners/edit.html.erb
<%= render "form", owner: @owner %>

app/views/owners/index.html.erb
<div class="container mt-4">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">RG</th>
        <th scope="col">Visualizar</th>
        <th scope="col">Editar</th>
      </tr>
    </thead>
    <tbody>
      <% @owners.each do |owner| %>
        <tr>
            <th scope="row"><%= owner.id %></th>
            <td><%= owner.name %></td>
            <td><%= owner.cpf %></td>
            <td><%= owner.rg %></td>
            <td><%= link_to 'Visualizar', owner_path(owner) %></td>
            <td><%= link_to 'Editar', edit_owner_path(owner) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%#= link_to 'Voltar', :back, class: 'btn btn-primary mt-3' %>
</div>


    

app/views/owners/new.html.erb
<%= render "form", owner: @owner %>

app/views/owners/show.html.erb
<div class="container mt-4">
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">RG</th>
        <th scope="col">Telefone</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <th scope="row"><%= @owner.id %></th>
          <td><%= @owner.name %></td>
          <td><%= @owner.cpf %></td>
          <td><%= @owner.rg %></td>
          <td><%= @owner.phone %></td>
        </tr>
    </tbody>
  </table>

  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">Endereço</th>
        <th scope="col">E-mail</th>
        <th scope="col">Estado Cívil</th>
        <th scope="col">Data de Nascimento</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @owner.address %></td>
          <td><%= @owner.email %></td>
          <td><%= @owner.marital_status %></td>
          <td><%= @owner.birthdate %></td>
        </tr>
    </tbody>
  </table>

  <div class="links text-center">
    <%= link_to 'Editar', edit_owner_path(@owner), class: 'btn btn-primary mb-3' %>
    <%= link_to "Excluir", @owner, method: :delete, data: { confirm: 'Tem certeza que deseja deletar este cliente?' }, class: 'btn btn-danger mb-3' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg", width: '50px' %>
  <% end %>

  <!-- Links -->
  <% if user_signed_in? %>
    <%#= current_user.first_name %>
    <ul class="navbar-nav w-100 justify-content-around">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          Proprietários
        </a>
        <div class="dropdown-menu bg-dark">
          <%= link_to 'Novo', new_owner_path, class: "dropdown-item text-light" %>
          <%= link_to 'Listar', owners_path, class: "dropdown-item text-light" %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          Propriedades
        </a>
        <div class="dropdown-menu bg-dark">
          <%= link_to 'Nova Propriedade', new_house_path, class: "dropdown-item text-light" %>
          <%= link_to 'Listar propriedades', houses_path, class: "dropdown-item text-light" %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          Locatarios
        </a>
        <div class="dropdown-menu bg-dark">
          <%= link_to 'Nova Locatário', new_locator_path, class: "dropdown-item text-light" %>
          <%= link_to 'Listar Locatários', locators_path, class: "dropdown-item text-light" %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          Contratos
        </a>
        <div class="dropdown-menu bg-dark">
          <%= link_to 'Contratos', contracts_path, class: "dropdown-item text-light" %>
          <%= link_to 'Novo Contrato', new_contract_path, class: "dropdown-item text-light" %>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  <% end %>
</nav>